spring.application.name=backend

server.address=0.0.0.0
server.port=8080

cors.allowed-origins=http://localhost:4200,http://localhost:3000

jwt.secret=AfTz6L1nK9sW8mP6rJvXqT7eUc1ZHa0OqWdGM7yVn2FjP4lXkS2rZb1cN4hW5e9A
jwt.token.access.expire.time=1800000
jwt.token.refresh.expire.time=604800000

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=note-app

google.client-id=733215044472-qgglfgkfvvtvtgg24t29lauuphtqqclp.apps.googleusercontent.com